<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="2" ignored="2" total="5" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-10-30T06:25:07 GMT" name="Default suite" finished-at="2025-10-30T06:25:37 GMT" duration-ms="29873">
    <groups>
    </groups>
    <test started-at="2025-10-30T06:25:07 GMT" name="Default test" finished-at="2025-10-30T06:25:37 GMT" duration-ms="29873">
      <class name="supermarketproject.HomePageTest">
        <test-method is-config="true" signature="browserInitialising()[pri:0, instance:supermarketproject.HomePageTest@14cd1699]" started-at="2025-10-30T06:25:07 GMT" name="browserInitialising" finished-at="2025-10-30T06:25:14 GMT" duration-ms="7132" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browserInitialising -->
        <test-method retried="true" signature="verifyLogout()[pri:0, instance:supermarketproject.HomePageTest@14cd1699]" started-at="2025-10-30T06:25:14 GMT" name="verifyLogout" finished-at="2025-10-30T06:25:17 GMT" duration-ms="2938" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Logout Failed!! expected [Login | 7rmart supermarket1] but found [Login | 7rmart supermarket]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Logout Failed!! expected [Login | 7rmart supermarket1] but found [Login | 7rmart supermarket]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at supermarketproject.HomePageTest.verifyLogout(HomePageTest.java:30)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLogout -->
        <test-method is-config="true" signature="captureScreenshotWhenTestCaseFail(org.testng.ITestResult)[pri:0, instance:supermarketproject.HomePageTest@14cd1699]" started-at="2025-10-30T06:25:17 GMT" name="captureScreenshotWhenTestCaseFail" finished-at="2025-10-30T06:25:18 GMT" duration-ms="970" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyLogout status=SKIP method=HomePageTest.verifyLogout()[pri:0, instance:supermarketproject.HomePageTest@14cd1699] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureScreenshotWhenTestCaseFail -->
        <test-method is-config="true" signature="browserInitialising()[pri:0, instance:supermarketproject.HomePageTest@14cd1699]" started-at="2025-10-30T06:25:18 GMT" name="browserInitialising" finished-at="2025-10-30T06:25:24 GMT" duration-ms="5690" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browserInitialising -->
        <test-method retried="true" signature="verifyLogout()[pri:0, instance:supermarketproject.HomePageTest@14cd1699]" started-at="2025-10-30T06:25:24 GMT" name="verifyLogout" finished-at="2025-10-30T06:25:26 GMT" duration-ms="2608" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Logout Failed!! expected [Login | 7rmart supermarket1] but found [Login | 7rmart supermarket]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Logout Failed!! expected [Login | 7rmart supermarket1] but found [Login | 7rmart supermarket]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at supermarketproject.HomePageTest.verifyLogout(HomePageTest.java:30)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLogout -->
        <test-method is-config="true" signature="captureScreenshotWhenTestCaseFail(org.testng.ITestResult)[pri:0, instance:supermarketproject.HomePageTest@14cd1699]" started-at="2025-10-30T06:25:26 GMT" name="captureScreenshotWhenTestCaseFail" finished-at="2025-10-30T06:25:27 GMT" duration-ms="1125" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyLogout status=SKIP method=HomePageTest.verifyLogout()[pri:0, instance:supermarketproject.HomePageTest@14cd1699] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureScreenshotWhenTestCaseFail -->
        <test-method is-config="true" signature="browserInitialising()[pri:0, instance:supermarketproject.HomePageTest@14cd1699]" started-at="2025-10-30T06:25:27 GMT" name="browserInitialising" finished-at="2025-10-30T06:25:33 GMT" duration-ms="5335" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browserInitialising -->
        <test-method signature="verifyLogout()[pri:0, instance:supermarketproject.HomePageTest@14cd1699]" started-at="2025-10-30T06:25:33 GMT" name="verifyLogout" finished-at="2025-10-30T06:25:35 GMT" duration-ms="2693" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Logout Failed!! expected [Login | 7rmart supermarket1] but found [Login | 7rmart supermarket]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Logout Failed!! expected [Login | 7rmart supermarket1] but found [Login | 7rmart supermarket]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at supermarketproject.HomePageTest.verifyLogout(HomePageTest.java:30)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLogout -->
        <test-method is-config="true" signature="captureScreenshotWhenTestCaseFail(org.testng.ITestResult)[pri:0, instance:supermarketproject.HomePageTest@14cd1699]" started-at="2025-10-30T06:25:35 GMT" name="captureScreenshotWhenTestCaseFail" finished-at="2025-10-30T06:25:37 GMT" duration-ms="1228" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyLogout status=FAILURE method=HomePageTest.verifyLogout()[pri:0, instance:supermarketproject.HomePageTest@14cd1699] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureScreenshotWhenTestCaseFail -->
      </class> <!-- supermarketproject.HomePageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
